CREATE OR REPLACE  ROLE ANALYST_ROLE;
CREATE OR REPLACE ROLE AGENT_ROLE;

-- Warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AGENT_ROLE;

-- Database + Schema
GRANT USAGE ON DATABASE ABCD_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA ABCD_DB.VALIDATED_ABC_SCHEMA TO ROLE ANALYST_ROLE;

GRANT USAGE ON DATABASE ABCD_DB TO ROLE AGENT_ROLE;
GRANT USAGE ON SCHEMA ABCD_DB.VALIDATED_ABC_SCHEMA TO ROLE AGENT_ROLE;

-- Tables
GRANT SELECT ON VALIDATED_AGENTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON VALIDATED_RISK TO ROLE ANALYST_ROLE;

GRANT SELECT ON VALIDATED_AGENTS TO ROLE AGENT_ROLE;
GRANT SELECT ON VALIDATED_RISK TO ROLE AGENT_ROLE;

GRANT ROLE ANALYST_ROLE TO USER SRIRAMSANKARTS;
GRANT ROLE AGENT_ROLE TO USER SRIRAMSANKARTS;


CREATE OR REPLACE ROW ACCESS POLICY REGION_POLICY
AS (region STRING)
RETURNS BOOLEAN ->
CASE
    WHEN CURRENT_ROLE() = 'ANALYST_ROLE' THEN TRUE
    WHEN CURRENT_ROLE() = 'AGENT_ROLE' AND UPPER(region) = 'SOUTH' THEN TRUE
    ELSE FALSE
END;

ALTER TABLE VALIDATED_AGENTS
ADD ROW ACCESS POLICY REGION_POLICY ON (region);



CREATE OR REPLACE MASKING POLICY EMAIL_MASK
AS (val STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() = 'ANALYST_ROLE' THEN val
    ELSE '****@masked.com'
END;


CREATE OR REPLACE MASKING POLICY PHONE_MASK
AS (val STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() = 'ANALYST_ROLE' THEN val
    ELSE 'XXXXXX' || RIGHT(val, 4)
END;



ALTER TABLE VALIDATED_AGENTS
MODIFY COLUMN email SET MASKING POLICY EMAIL_MASK;

ALTER TABLE VALIDATED_AGENTS
MODIFY COLUMN phone SET MASKING POLICY PHONE_MASK;


USE ROLE ANALYST_ROLE;

SELECT * FROM VALIDATED_AGENTS;


USE ROLE AGENT_ROLE;

SELECT * FROM VALIDATED_AGENTS;
