CREATE OR REPLACE DATABASE ABCD_DB;
CREATE OR REPLACE SCHEMA RAW_ABC_SCHEMA;
CREATE OR REPLACE SCHEMA VALIDATED_ABC_SCHEMA;
CREATE OR REPLACE SCHEMA CURATED_ABC_SCHEMA;

USE DATABASE ABCD_DB;

USE SCHEMA RAW_ABC_SCHEMA;
